services:
    search:
        class: Evheniy\SearchBundle\Model\Index\Searcher
        arguments: [@service_container]

    search_index:
        class: Evheniy\SearchBundle\Model\Index\Indexer
        arguments: [@service_container]